# Generated by Django 5.1.7 on 2025-03-20 14:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourist_spots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_adicionado', models.DateTimeField(default=django.utils.timezone.now)),
                ('ponto_turistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='tourist_spots.touristspot')),
            ],
        ),
    ]
