# Generated by Django 5.1.7 on 2025-03-20 14:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('cidade', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('categoria', models.CharField(choices=[('natural', 'Atração Natural'), ('historical', 'Ponto Histórico'), ('cultural', 'Atração Cultural'), ('adventure', 'Aventura'), ('religious', 'Religioso'), ('gastronomic', 'Gastronômico'), ('other', 'Outro')], max_length=20)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TouristSpotImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to='tourist_spots/')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('ponto_turistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='tourist_spots.touristspot')),
            ],
        ),
    ]
